#version 450

layout(local_size_x = 8, local_size_y = 8) in;

#include "post_processing/bloom/blur_common.h"

const float SCALE = 1.75;

void main()
{
    if (all(lessThan(gl_GlobalInvocationID.xy, common_uniform.resolution)))
    {
        vec2 uv = (vec2(gl_GlobalInvocationID.xy) + 0.5) * common_uniform.inv_resolution;
        vec3 rgb = bloom_blur(uv, SCALE);
        imageStore(out_tex, ivec2(gl_GlobalInvocationID.xy), vec4(rgb, 1.0));
    }
}